spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pg_project
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: ${PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  boot:
    admin:
      mail:
        to: ${spring.mail.username}
        from: ${spring.mail.username}
  mail:
    host: smtp.gmail.com
    username: testmail29032023@gmail.com
    password: ${ADMIN_PASSWORD}
    port: 587
    protocol: smtp
    properties:
      "mail.transport.protocol": smtp
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
jwt:
  expiration: 360000
  secret: gthtvjuf

server:
  port: 8081